### ISSUE TITLE
VideoEncodingMuxing项目编译出错问题

### ISSUE THREAD

**Issue by chenqy2018** [yinwenjie/FFmpeg_Tutorial#1]
>  EncodingMuxingMain.cpp
> 1>c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: “snprintf”: 宏重定义
> 1>  e:\project\ffmpeg\videoencodingmuxing\encodingmuxingheader.h(4): note: 参见“snprintf”的前一个定义
> 1>c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration
> 1>  EncodingMuxingAudio.cpp
> 1>c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: “snprintf”: 宏重定义
> 1>  e:\project\ffmpeg\videoencodingmuxing\encodingmuxingheader.h(4): note: 参见“snprintf”的前一个定义
> 1>c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration
> 1>  CoderMuxer.cpp
> 1>c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(1925): warning C4005: “snprintf”: 宏重定义
> 1>  e:\project\ffmpeg\videoencodingmuxing\encodingmuxingheader.h(4): note: 参见“snprintf”的前一个定义
> 1>c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt\stdio.h(1927): fatal error C1189: #error:  Macro definition of snprintf conflicts with Standard Library function declaration
> 1>  正在生成代码...
> ========== 生成: 成功 0 个，失败 1 个，最新 0 个，跳过 0 个 ==========

去掉#define snprintf(buf,len, format,...) _snprintf_s(buf, len,len, format, __VA_ARGS__)
就会出现更多的错误，请问这个有什么办法解决吗？？？

**Comment by yinwenjie** [comment]
VS2015编译的？还是include了其他STL的头文件？

**Comment by yinwenjie** [comment]
建议暂时使用VS2013到VS2010的版本编译，VS2015改动比较大，而且我这里暂时没法安装，所以没经过测试。

**Comment by chenqy2018** [comment]
ok  谢谢
