### ISSUE TITLE
你好，这个为什么会报错啊？

### ISSUE THREAD

**Issue by hongtianpei1990gmail** [yinwenjie/FFmpeg_Tutorial#3]
![image](https://cloud.githubusercontent.com/assets/17697229/20239292/2f072b34-a938-11e6-9157-32a812e241ce.png)
我有头部在引入C的类啊，
![image](https://cloud.githubusercontent.com/assets/17697229/20239297/4921d15e-a938-11e6-8c2b-65312e0baf7b.png)
为什么说会找不到fread_s 这个函数呢？我这个是从你的demo里面把代码复制到我们Ios工程中，我的开发我不是用visual studio,我用的是xcode7.2 ，能告诉我是哪里出问题了吗？

**Comment by yinwenjie** [comment]
你好，已在csdn私信回复，谢谢关注！
